#----------------------------------------------------------------------
# This file was generated by E:\Projects\github\MyTerm\icon\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAz9J"
    "REFUWIXlVs9L40AU/pJMFRWKELwZ/SMEQQi4ngQR/CdEj9vVg4ceakHvey142asnEX9QEGEh"
    "UFHqyYP0tCB4Moe10CQzk8keZIZJmmq72LKwDx5J05d83/veezMD/O9m3N3dTV9fX1c8zyuN"
    "Eth13e97e3vfyP39fcnzvJLjOJiYmBgJeBAE8DyvVKvVfpNms7ls2zbK5fJIwKWVy2U0m81l"
    "AgC2bQMAXl9fUalU8PT0NBRQx3FQrVZRLBZh2zba7TaIHnB0dITj4+OhgANAo9GA4zjY2dlR"
    "z0he4MbGBsbHx1M+NjbW9ZsQAsMwwDkHpRRRFKmr7pRShGGIk5OTLiwzj4BhGJifn8fW1hbm"
    "5ubUM9M0YRiGuieEgBAC0zTVfzJWv3/PchVIkgQzMzNwXReu6+Li4gJXV1cQQkAIgTiOwTlX"
    "AJxzcM6RJAmSJIEQAkmSqG+9Z7kKCCFwe3uLw8NDvLy8YG1tDbu7uygUCuCcgzGGKIoQBAE6"
    "nQ7CMARjDIwxcM4Rx7FySVgI0b8C8qV2u41Op6MykSBCCHDOlbxJkihV3iPSNwHOOZaWltTa"
    "UK/XcX5+DsYYCCHgnMOyrBQBvTSShE5GlqwvAowxPD8/4+bmBpeXl2i1WiCEYHFxEaurq10N"
    "1mq1cHp6qpSRzhgDpVQRGYjA4+MjqtUqCCEoFAqI4xiUUszOzmJycjIV//DwgCAIlAq6EnJE"
    "ByJAKVUdLevHOYfneWg0Gl1jl42VJCSBgRWIoihV1ziOYVmWcjnn+ozLeL0XZCNKIgMpIIRQ"
    "Cw0hBJZlqcyl6yZnXx87vR8GIhBFUaqWevb6apgtQVYF+b6+cPVFIAzDVOY6uE4AeJuEPAJZ"
    "En+lgMzeNM2eBKRlSeiLkPSBFLAsS200WXBZf70E8prtBV2FgQno0svuz+56vRTQm3FgBWTj"
    "SMC85svrASA9Dbr32hVzCegZ6RtPHriMzarw0Tb8IYFehD7bUgQ2Nzc/HSBrWQwCAL7vIwgC"
    "FIvF1IFxWBYEAXzffztXLiws/Dw7O/tycHCgjufDNt/34fs+1tfXfxoAUKvV9uv1+lfG2PQo"
    "CExNTf1aWVn5sb29vT8KvH/b/gArZAfevTaT9AAAAABJRU5ErkJggg==")
geticon32Data = icon32.GetData
geticon32Image = icon32.GetImage
geticon32Bitmap = icon32.GetBitmap
geticon32Icon = icon32.GetIcon

